# Change these first
owner: justbecauseph # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Coffeenow
    url: https://coffeenow.ph
    maxResponseTime: 3000
    expectedStatusCodes:
      - 200
      - 201
      - 404
      - 403
  - name: Aljoetravel
    url: https://aljoetravel.com
    maxResponseTime: 3000
  - name: Rexulili
    url: https://rxl.gg
    maxResponseTime: 3000
  - name: JustBecause
    url: https://justbecause.ph
    maxResponseTime: 3000
assignees:
  - awkwardusername
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.justbecause.ph
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/justbecauseph/upptime/refs/heads/master/assets/justbecauseph.png
  name: JustBecause Status
  introTitle: "Managed by **JustBecause**"
  introMessage: "contact: hello at justbecause dot ph"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
runner: "[self-hosted]"
user-agent: justbecauseph
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
